version: "3.4"
services:
  gov-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_PREFIX:-dovu/gov}-api:${DOCKER_IMAGE_TAG:-local}
    restart: always
    ports:
      - ${SERVER_API_PORT}:80
    environment:
      - MIRROR_GRPC=${MIRROR_GRPC}
      - MIRROR_REST=${MIRROR_REST}
      - HCS_TOPIC=${HCS_TOPIC}
      - HTS_TOKEN=${HTS_TOKEN}
      - HCS_START_DATE=${HCS_START_DATE}
