version: "3.4"
services:
  gov-ui:
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
        API_ENDPOINT: ${WEBAPP_API_ENDPOINT:-http://localhost:${SERVER_API_PORT}}
    image: ${DOCKER_IMAGE_NAME:-dovu/gov-ui}:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - ${WEBAPP_PORT}:80
    depends_on:
      - gov-api
